#!/bin/bash
# Description: Freshen up the project's dependencies and data
# Meta: order=3

print_banner "Freshening up the project's dependencies and data..."

docker_compose_up_if_necessary

# run: composer install
# run: npm install

print_divider
