#!/bin/bash
# Description: Bring the project up
# Meta: order=2

prevent_running_inside_container

print_banner "Bringing the project up..."

docker_compose_up

# if has_option "--fresh"; then
#     run: composer install
# fi

print_divider
