#!/bin/bash
# https://xscripts.sh - XScripts To Rule Them All
# Version: 0.1.0

readonly XSCRIPTS_DIR="$(dirname "$0")/.xscripts"
readonly IS_DOCKER_COMPOSE_ENVIRONMENT=$((test -f ./docker-compose.yml || test -f ./docker-compose.yaml) && echo true || echo false)
readonly IS_INSIDE_DOCKER_CONTAINER=$((test -f /.dockerenv) && echo true || echo false)
declare -a COMMANDS

source $XSCRIPTS_DIR/__xscripts

::load_libraries_and_commands

# figure out the environment
if [ "$IS_DOCKER_COMPOSE_ENVIRONMENT" = true ]; then
  # get the name of the first service in the docker-compose file
  SERVICE_NAME=$(parse_yaml ./docker-compose.yml | grep services | head -n 1 | cut -d "_" -f 2)
fi

# there must be at least one argument
if [ -z "$1" ]; then
  print_help
  exit 0
fi

REQUESTED_COMMAND="$1"

if [ "$REQUESTED_COMMAND" = "make" ]; then
  ::make_command "$2"
  exit 0
fi

# get the requested script from COMMANDS
REQUESTED_SCRIPT=$(echo ${COMMANDS[@]} | tr ' ' '\n' | grep "$REQUESTED_COMMAND" | cut -d "=" -f 2)
REQUESTED_SCRIPT_PATH="$XSCRIPTS_DIR/$REQUESTED_SCRIPT"

if [ ! -f "$REQUESTED_SCRIPT_PATH" ]; then
  echo "Script not found: $REQUESTED_SCRIPT_PATH"
  print_help
  exit 1
fi

source $REQUESTED_SCRIPT_PATH

exit 0
